import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "../app/styles/reset.scss";
import "../app/styles/globals.scss";
import "../app/styles/typography.scss"

const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal"],
  variable: "--font-roboto",
})

export const metadata: Metadata = {
  title: "Buzzvel Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
