import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import Head from "next/head";
import "../app/styles/reset.scss";
import "../app/styles/globals.scss";
import "../app/styles/typography.scss";

const roboto = Roboto({
  subsets: ["cyrillic"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Buzzvel Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="author" content="Wallace Menezes" />
        <meta name="keywords" content="Buzzvel, Teste de Desenvolvimento, Next.js" />
        <meta name="robots" content="index, follow" />
        
        <meta property="og:title" content="Buzzvel Test" />
        <meta property="og:description" content="Generated by create next app" />
        <meta property="og:image" content="/path-to-image.jpg" />
        <meta property="og:url" content="https://your-deployment-url.com" />
        <meta property="og:type" content="website" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Buzzvel Test" />
        <meta name="twitter:description" content="Generated by create next app" />
        <meta name="twitter:image" content="/path-to-image.jpg" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
      </Head>
      <body className={`${roboto.variable}`}>
        {children}
      </body>
    </html>
  );
}
